In [1]:
import numpy

In [2]:
import numpy 
arr = numpy.array([1,2,3,4,5])

print(arr)


[1 2 3 4 5]


In [3]:
import numpy as np 
arr = np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


In [4]:
print(np.__version__)

2.0.2


In [5]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
tmp = np.ndarray([1,2,3,4,5])
print(tmp)

[[[[[0.00000000e+000 6.95184870e-310 4.47623475e-321             nan
     1.12646967e-321]
    [0.00000000e+000 1.61356517e+184 2.89382441e+227 1.48345685e-119
     4.00979049e+087]
    [1.02189324e-152 1.33856865e-152 2.59345432e+161 2.16402759e+233
     7.74412838e+228]
    [1.12038868e+219 1.23701654e-259 9.23546148e+242 2.52960802e-258
     4.47593804e-091]]

   [[2.44041296e-154 1.14115712e+243 5.44533295e-096 7.57782077e+005
     2.18379531e-094]
    [2.13945866e+161 6.01347002e-154 3.77678522e+180 8.72944715e+183
     2.45650347e+198]
    [2.05105506e+161 6.39374609e+246 1.66036929e+243 6.01334515e-154
     1.71577771e-119]
    [2.35567916e+251 5.30479557e+180 2.11329292e+214 4.99955024e+228
     2.18145537e+243]]

   [[6.01346953e-154 3.42774111e+214 1.14115712e+243 3.77678520e+180
     8.72944715e+183]
    [2.45650347e+198 8.51883418e+223 2.46563539e-154 1.91002772e+227
     1.33717019e-152]
    [6.51684233e+029 8.95529995e-106 8.11279884e+228 4.53146453e+217
     2.44015728e-

In [7]:
# dimensions in Arrays.
# 0-D array (Scalar).
import numpy as np
arr = np.array(36)

print(arr)

36


In [8]:
# 1-D array.
import numpy as np
arr = np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


In [9]:
# 2-D array.
import numpy as np
arr = np.array([ [1,2,3], [4,5,6] ] )

print(arr)

[[1 2 3]
 [4 5 6]]


In [10]:
# 3-D array.
import numpy as np
arr = np.array([ [ [1,2,3], [4,5,6], [7,8,9], [10,11,12] ] ])

print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [11]:
print(arr[0])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
print(arr[0][0])

[1 2 3]


In [13]:
print(arr[0][0][0])

1


In [14]:
print(arr[0][1])

[4 5 6]


In [15]:
print(arr[0][2])

[7 8 9]


In [16]:
print(arr[0][3])

[10 11 12]


In [17]:
print(arr[0][3][2])

12


In [18]:
tmp = np.array([1,2, "abc", "def"])

In [19]:
print(tmp)

['1' '2' 'abc' 'def']


In [20]:
print(arr.ndim)

3


In [21]:
a = np.array(57)
b = np.array([1,2,3,4,5])
c = np.array([ [1,2,3], [4,5,6]])
d = np.array([[ [1,2,3], [4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [22]:
import numpy as np
arr = np.array([1,2,3,4], ndmin=5)

print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


In [23]:
arr = np.array([1,2,3,4])

print(arr[2] + arr[3])

7


In [24]:
arr = np.array([[ [1,2,3], [4,5,6], [7,8,9]]])
print(arr[0])
print(arr[0][1])
print(arr[0][1][2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
6


In [25]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10] ])
print(arr[1,-1])
print(arr[1,-3])
print(arr[0,-3])


10
8
3


In [26]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[1:5])

[2 3 4 5]


In [27]:
print(arr[1:8])
print(arr[1:8:2])
print(arr[0:8:2])

[2 3 4 5 6 7 8]
[2 4 6 8]
[1 3 5 7]


In [28]:
print(arr[1:8:3])

[2 5 8]


In [29]:
print(arr[4:])

[ 5  6  7  8  9 10]


In [30]:
print(arr[:4])

[1 2 3 4]


In [31]:
print(arr[-3:-1])

[8 9]


In [32]:
print(arr[::2])

[1 3 5 7 9]


In [33]:
arr = np.array( [ [1,2,3,4,5], [6,7,8,9,10]])
print(arr[1, 1:4])   # 2,3,4 OR 7,8,9,10 OR 7,8,9
print(arr[1][1:4])

[7 8 9]
[7 8 9]


In [34]:
print(arr[0:2,2])     # arr[0:2][2]     prints 3,8 OR 

[3 8]


In [35]:
print(arr[0:2][1:4])     # not preferred.


[[ 6  7  8  9 10]]


In [36]:
print(arr[0:2,1:4])     # preferred.

[[2 3 4]
 [7 8 9]]


In [37]:
arr = np.array([1,2,3,4,5])
newArr = arr.copy()

print(arr)
print(newArr)

[1 2 3 4 5]
[1 2 3 4 5]


In [38]:
arr[0] = 76
print(arr)
print(newArr)

[76  2  3  4  5]
[1 2 3 4 5]


In [39]:
newArr[2] = 50
print(arr)
print(newArr)

[76  2  3  4  5]
[ 1  2 50  4  5]


In [40]:
arr = np.array([1,2,3,4,5])
newArr = arr.view()

print(arr)
print(newArr)

[1 2 3 4 5]
[1 2 3 4 5]


In [41]:
arr[0] = 76
print(arr)
print(newArr)

[76  2  3  4  5]
[76  2  3  4  5]


In [42]:
newArr[2] = 50
print(arr)
print(newArr)

[76  2 50  4  5]
[76  2 50  4  5]


In [43]:
arr = np.array([1,2,3,4,5])

copyArr = arr.copy()
viewArr = arr.view()

print(copyArr)
print(viewArr)

# If it returns "None", it is a copy and owns the data.
print(copyArr.base)    
print(viewArr.base)


[1 2 3 4 5]
[1 2 3 4 5]
None
[1 2 3 4 5]


In [44]:
# Iterating.
arr = np.array([1,2,3,4,5])
for i in arr:
    print(i)

1
2
3
4
5


In [45]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
for i in arr:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
10


In [46]:
arr = np.array([[[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]]])
for i in arr:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [47]:
arr = np.array([[[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [48]:
arr = np.array([[[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]]])
for indx, x in np.ndenumerate(arr):
    print(indx, x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 5
(0, 1, 0) 6
(0, 1, 1) 7
(0, 1, 2) 8
(0, 1, 3) 9
(0, 1, 4) 10
(0, 2, 0) 11
(0, 2, 1) 12
(0, 2, 2) 13
(0, 2, 3) 14
(0, 2, 4) 15


In [49]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [50]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

arr = np.concatenate((arr1, arr2))
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [51]:
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [52]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

arr = np.stack((arr1,arr2), axis=1)
print(arr)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [53]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

arr = np.stack((arr1,arr2))
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [54]:
arr1 = np.array([1,2,3,4,5,6])

arr = np.array_split(arr1,3)
print(arr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [55]:
arr1 = np.array([1,2,3,4,5,6,7])

arr = np.array_split(arr1,3)
print(arr)

[array([1, 2, 3]), array([4, 5]), array([6, 7])]


In [56]:
arr1 = np.array([1,2,3,4,5,6])

arr = np.array_split(arr1,4)
print(arr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [57]:
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])


[1 2]
[3 4]
[5]
[6]


In [58]:
arr1 = np.array([[1,2],[3,4], [5,6],[7,8], [9,10]])

arr = np.array_split(arr1, 3)
print(arr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10]])]


In [59]:
arr = np.array([1,2,3,4,5,6,7])
srch = np.where(arr == 4)
print(srch)


(array([3]),)


In [60]:
arr = np.array([1,2,3,4,5,4,6,7,4])
srch = np.where(arr == 4)
print(srch)

(array([3, 5, 8]),)


In [61]:
print(arr[srch])

[4 4 4]


In [62]:
arr = np.array([1,2,3,4,5,6,7,8])
srch = np.where(arr %2 == 0)
print(srch)

(array([1, 3, 5, 7]),)


In [63]:
arr = np.array([1,2,3,4,5,6,7,8])
srch = np.where(arr %2 == 1)
print(srch)

(array([0, 2, 4, 6]),)


In [64]:
arr = np.array([5,6,8,9])
x = np.searchsorted(arr, 7)
print(x)


2


In [65]:
arr = np.array([8,6,9,5])
x = np.searchsorted(arr, 7)
print(x)


2


In [66]:
arr = np.array([4,5,6,8,9])
x = np.searchsorted(arr, 7, side="right")
print(x)


3


In [67]:
arr = np.array([1,3,5,7])
x = np.searchsorted(arr, [2,4])
print(x)


[1 2]


In [68]:
arr1 = np.array([8,6,9,5])
arr = np.sort(arr1)

print(arr)

[5 6 8 9]


In [69]:
arr1 = np.array(["strawberry", "apple", "orange", "banana",])
arr = np.sort(arr1)

print(arr)

['apple' 'banana' 'orange' 'strawberry']


In [70]:
arr1 = np.array([15,16,17,18])
filter = [True, False, True, False]

newArr = arr1[filter]
print(newArr)

[15 17]


In [71]:
arr1 = np.array([15,16,17,18])
filter = [True, False, False, True]

newArr = arr1[filter]
print(newArr)

[15 18]


In [72]:
arr1 = np.array([15,16,17,18])
filter = [True, False, False, True]

newArr = arr1[filter]
print(newArr)

[15 18]


In [73]:
arr1 = np.array([15,16,17,18, 19, 20])
filter = arr1 > 18

newArr = arr1[filter]
print(filter)
print(newArr)

[False False False False  True  True]
[19 20]


In [74]:
arr1 = np.array([15,16,17,18, 19, 20])
filter = arr1 %2 == 0

newArr = arr1[filter]
print(filter)
print(newArr)

[False  True False  True False  True]
[16 18 20]
